services:
  api:
    build: ./api
    env_file:
      - api/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/readyz"]
      interval: 10s
      timeout: 3s
      retries: 5
    # For local dev hot-reload, uncomment:
    # volumes:
    #   - ./api:/app
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


